name: Cypress Tests

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  FRONTEND_PATH: ./

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./

      - name: Start the application
        run: npm start &
        working-directory: ./

      - name: Wait for the application to be ready
        run: npx wait-on http://localhost:4200 

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: ./

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos/
            cypress/screenshots/
            cypress/cucumber-json/
          if-no-files-found: ignore